#! /usr/bin/bash
#
# little script to update po files 
#

LOCATIONS=`ls -1 --color=none libchristine/*py` 
LOCATIONS="$LOCATIONS `ls -1 --color=none libchristine/pattern/*py`"
LCOATIONS="$LOCATIONS `ls -1 --color=none gui/*glade`"

TRANSLATIONS="christine es_ES"

for i in $TRANSLATIONS; do
	echo "$i.po"
	if [ "x$i" == "xchristine" ]; then
		end='pot';
	else
		end='po';
	fi
	xgettext -p po -j -o $i.$end -l --keyword=translate --keyword=_N --from-code=Glade $LOCATIONS
done
