#! /usr/bin/bash
#
# little script to update po files 
#

####LOCATIONS=`ls -1 --color=none libchristine/*py` 
####LOCATIONS="$LOCATIONS `ls -1 --color=none libchristine/pattern/*py`"
####LOCATIONS="$LOCATIONS `ls -1 --color=none libchristine/Plugins/*py`"
####for i in albumCover christinePyNotify getInfo gnomeDBus lastfm pidgin trayicon twitter; do
####	LOCATIONS="$LOCATIONS `ls -1 --color=none libchristine/$i/*py`"
####done

####LOCATIONS="$LOCATIONS `ls -1 --color=none libchristine/gui/*py`"
####LOCATIONS="$LOCATIONS `ls -1 --color=none libchristine/Storage/*py`"
####LOCATIONS="$LOCATIONS `ls -1 --color=none gui/*glade`"
LOCATIONS=`find -iname "*py"`;

TRANSLATIONS="christine es_ES ca cs da de el en_GB  eu fr hu it nl pt sv_FI sv"

for i in $TRANSLATIONS; do
	if [ "x$i" == "xchristine" ]; then
		end='pot';
		xgettext -p po  -o $i.$end -l --keyword=translate --keyword=_N --keyword=_ --from-code=Glade $LOCATIONS
	else
		end='po';
		xgettext -p po -j -o $i.$end -l --keyword=translate --keyword=_N --keyword=_ --from-code=Glade $LOCATIONS
	fi
	echo "$i.$end"

done
